services:
  media-server:
    build:
      context: ./media-server
      dockerfile: Dockerfile
    environment:
      - IS_DOCKER=true
      - ROOT_DIRECTORY=/mnt/ssd
      - FILE_DB_PATH=/mnt/ssd/file_paths.db
      - MEDIA_SERVER_PORT=${MEDIA_SERVER_PORT}
      - SERVER_URL=http://localhost:${MEDIA_SERVER_PORT}
    volumes:
      - '${DOCKER_VOLUME_PATH}:/mnt/ssd'
      - './db:/mnt/ssd' # Mount a local db folder to the same container path
    ports:
      - '${MEDIA_SERVER_PORT}:${MEDIA_SERVER_PORT}'
    command: >
      sh -c "
        echo 'Initializing database if needed...' &&
        node /app/tools/index-folder.js &&
        echo 'Starting server...' &&
        node /app/server.js
      "

  media-viewer:
    build:
      context: .
      dockerfile: ./media-viewer/Dockerfile
    environment:
      - SERVER_URL=http://media-server:${MEDIA_SERVER_PORT}
    ports:
      - '5000:5000'
    volumes:
      - ./media-viewer/dist/media-viewer/browser:/app/dist:ro
    depends_on:
      - media-server
