services:
  media-server:
    build:
      context: ./media-server
      dockerfile: Dockerfile
    environment:
      - IS_DOCKER=true
      - ROOT_DIRECTORY=/mnt/ssd
      - FILE_DB_PATH=/mnt/ssd/file_paths.db
      - MEDIA_SERVER_PORT=4001
      - SERVER_URL=http://localhost:4001
    volumes:
      - 'C:\Users\Ubaby\Pictures\Screenshots:/mnt/ssd'
    ports:
      - '4001:4001'
    command: >
      sh -c "
        echo 'Initializing database if needed...' &&
        node /app/tools/index-folder.js &&
        echo 'Starting server...' &&
        node /app/server.js
      "

  media-viewer:
    build:
      context: .
      dockerfile: ./media-viewer/Dockerfile
    environment:
      - SERVER_URL=http://media-server:4001
    ports:
      - '5000:5000'
    volumes:
      - ./media-viewer/dist/media-viewer/browser:/app/dist:ro
    depends_on:
      - media-server
